### ISSUE TITLE
Can't Log In PHP 7.1 and 7.2

### ISSUE THREAD

**Issue by Richb2021** [ihofmann/open-websoccer#106]
I've managed to install the latest version and rolled PHP back to 7.2 and 7.1 but still can't login to the admin portal, any ideas on what I could do to fix it?

It can tell when I've used an incorrect password, but just asks me to log in when I use the correct password. Any help would be greatly appreciated!!

**Comment by Sasuke-SR** [comment]
Only work for PHP 5.6 or below
