### ISSUE TITLE
Premium Scripts for HSE Websoccer 5.2.3

### ISSUE THREAD

**Issue by WSFeatures** [ihofmann/open-websoccer#129]
SQL Query | Check duplicate players | 15 Euros
SQL Query | Check negative budget | 5 Euros
SQL Query | Check sponsor | 5 Euros
SQL Query | Check negative budget | 5 Euros
SQL Query | Check min. Team size | 5 Euros
SQL Query | Check max. Team size | 5 Euros
Database Administration page | 50 Euros
Cronjob | Optimize Database | 25 Euros
Cronjob | Move clubless players | 20 Euros
Cronjob | Disable inactive users | 30 Euros
Cronjob | Strength and Salary Automation | 60 Euros

All of them are openAI optimized and has been fully tested.

Regards

**Comment by aykutgunes06** [comment]
How can I contact you?

**Comment by WSFeatures** [comment]
info@cardsch.shop

All scripts are still available

regards

**Comment by WSFeatures** [comment]
@aykutgunes06

Contact is in the original post

Regards

**Comment by joseborges** [comment]
New link for anyone interested in openwebsoccer free development (hopefully this one doesn't expire)

https://discord.com/invite/6kWjdMY6Kx

**Comment by WSFeatures** [comment]
@joseborges 

Doesnt see any context to my post here 😉
