### ISSUE TITLE
Funktion fehlt: Transfer durch Admin freigeben

### ISSUE THREAD

**Issue by teamchef** [ihofmann/open-websoccer#3]
Sie hatten ja geschrieben bei Sim Raisal wenn man einen Fehler findet dies hier zu melden.

 Im Websoccer kann man ja  Ein vereinbarter Direkttransfer muss von einem Administrator genehmigt werden einstellen aber ich kann die Transfers nicht als Admin freigeben die Funktion fehlt im Admin bereich.

**Comment by ihofmann** [comment]
War ein Bug und ist im Release 5.2.3 gefixt. Update kann unter "Releases" heruntergeladen werden.
