### ISSUE TITLE
AdminPanel and installation problems

### ISSUE THREAD

**Issue by elBandoler** [ihofmann/open-websoccer#34]
Hey, just downloaded, uploaded and did everything as it said in the Wiki.
At first, I had no labels on the installation, but I got over it (Inspecting Element).
Now I am having a problem when trying to log into the administrator account.
I'm at mydomain.com/admin/login.php and no matter what I do, I just get the same page, asking me to log in again.
Tried to create a user in the site itself, works perfectly, logged in perfectly.
Help?

**Comment by Requiao** [comment]
What is the PHP version? If it is PHP 7 it will not work. Only works with PHP 5.6

**Comment by Blaumut** [comment]
I'm using a VPS with Sentora CP to host websites.
I checked through the panel, and it says PHP Version 5.5.9-1ubuntu4.21.
I assume that's the problem. 
Any idea on how to upgrade to 5.6? Or is 5.5.9 good enough?

**Comment by Requiao** [comment]
Yes. I use PHP 5.6, 
I know others have had problems with different versions of PHP. 
You have downloaded which version of WebSoccer Sim?
Do you have an email address? It's easier. My email is adilson.requiao @gmail.com

**Comment by Blaumut** [comment]
Well, installed 5.6, removed 5.5.9.
The installation still doesn't have any label.
Here's a picture of that screen: https://i.gyazo.com/3357a9f51d556692c534286e08706760.png
I can still understand what each line is, but I don't know if I should continue the installation.
Help?

**Comment by Requiao** [comment]
ok.
my email: adilson.requiao@gmail.com

I sent mail to you.
