### ISSUE TITLE
Removing empty files from code base

### ISSUE THREAD

**Issue by rolfjoseph** [ihofmann/open-websoccer#4]
Hallo Herr Hofmann,

im Verzeichnis admin/config sind folgende Dateien mit 0 Bytes:

adminlog.php
config.inc.php
entitylog.php
lockfile.txt

Ich bitte Sie diese ab dem nächsten Update raus zu nehmen. Wenn man das volle Verzeichnis runterlädt und aufspielt werden die vorhandenen Dateien überschrieben, was bei der config.inc.php fatal ist, wenn man kein Update gemacht hat. Das Programm OurWebFTP auf meinem Server mag z.B. keine 0 Byte Dateien und stoppt spätestens bei der lockfile.txt. So sind Sicherungen des aktuellen Systems auch nur mit unnötigen Eingriffen möglich.

Das Update-Verzeichnis sollte auch nur die Dateien enthalten, die geändert wurden. Das augenblickliche Update enthält sehr viele Dateien, welche nicht geändert wurden. So kann man nicht sehen, welche geändert sind. Spielt man nun das Update auf, so werden evt. auch eigene Änderungen an anderen Dateien überschrieben. 

Zum einfacheren Handling bitte ich sie dies zu berücksichtigen.

Rolf Joseph / ErdemCan

**Comment by ihofmann** [comment]
An English summary for interested developers:

It appears that some FTP clients cannot handle empty files (see list of files in issue description).
Suggestion:

* Add some content to lockfile.txt, e.g. purpose of file (shall prevent concurrent job executions).
* Use new writable folder for creating and writing remaining files and add folder content to .gitignore. Make sure the new folder is mentioned at the installation manual and in the installation routine.

Feel free to contribute the code. :)

**Comment by ihofmann** [comment]
Resolved as suggested. The generated files were moved to /generated. The update routine will automatically move the files.
