### ISSUE TITLE
Webservice

### ISSUE THREAD

**Issue by moritz2212** [ihofmann/open-websoccer#52]
Hello,
has anyone Knowledge in webservices? I'd like to implement on to ease the work with Jobs and to trigger Jobs via webservices instead.

**Comment by moritz2212** [comment]
done, activated token for external Access. works fine.

**Comment by Requiao** [comment]
What have you been able to do?

**Comment by moritz2212** [comment]
first of all you Need to activate external Access with a key in admin->Settings section
then you call the Jobs defined under admin/config/Jobs.xml via Website or other script such python.
e.g. http://YOUR_WEBSITE/webservices/executeJob.php?sectoken=b7MPgSp7WGxxzb12kfr042DytuwhT&jobid=sim

Parameters:
sectoken = token or security key defined in admin section
jobid = Job ID defined in Jobs.xml

**Comment by Requiao** [comment]
Very nice!

**Comment by japetos** [comment]
little python example script:
`import threading
import urllib2
import datetime

def sim():
    threading.Timer(5.0, sim).start()
    
    # get settings from settings.ini file
    #config = ConfigParser.ConfigParser()
    #config.read("settings.ini")
    #jobUrl = config.get("JOBID", "sim")
    
    jobUrl = 'http://YOUR_WEBSITE/webservices/executeJob.php?sectoken=b7MPgSp7WGxxzb12kfr042DytuwhT&jobid=sim'
    
    response = urllib2.urlopen(jobUrl)
    html = response.read()
    actual_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    txt = "%s - %s" % (actual_date,html)
    print txt
     
sim();`

script is executed every 5.0 seconds and the following paramaters need to be set in jobs.xml:
`<job id="sim" name="Execute Games and Transfers" name_de="Spiele und Transfers updaten" class="ExecuteGamesTransfersJob" interval="1" last_ping="1462865122" stop="0" error="" inittime="0"/>`

**Comment by Snodge** [comment]
Wheres the Admin key/token?

**Comment by japetos** [comment]
in DB, specified in Admin Section
