### ISSUE TITLE
Email not sent

### ISSUE THREAD

**Issue by dannyx93** [ihofmann/open-websoccer#60]
I tried registration in my game but I get error "email not sent". On my hosting PHPmail() is disable. How do it user activation?

**Comment by dannyx93** [comment]
I SOLOVED PROBLEM.

**Comment by JossyMall** [comment]
How did you do it?

**Comment by dannyx93** [comment]
I used phpmailer. I modify files pen-websoccer/websoccer/classes/EmailHelper.class.php

**Comment by Elessair** [comment]
can you please share here how you solved it?

I have similar issue
