### ISSUE TITLE
php7 version

### ISSUE THREAD

**Issue by joseborges** [ihofmann/open-websoccer#90]
is there already any FULL php7 fork compatible version of this?

Trying to make it work on PHP7, got the installer working correctly, them started to look into the login section but not sure where to fix whats broken.

If you did some progress on this care to share?

**Comment by nafbanap** [comment]
The master branch should be compatible with php 7.0 by now.
What is the specific php version you were looking for compatibility with?

**Comment by joseborges** [comment]
I'm trying on "localhost" running php7. 4, and I fixed a warning on 
https://github.com/ihofmann/open-websoccer/blob/f9f844708671ff666ff988b16b1970edab6aa08e/websoccer/install/index.php#L589 

by changing it to:

`If ($path[strlen ($path) -1] =='/') // recursively return a temporary file path`

So that I don't get any warnings, but when the game "installs", apparently all is well, but when I try to login as admin I can't.

Going through this issue I saw that the answer was always: can't login as admin? Use PHP 5.6.

**Comment by nafbanap** [comment]
If this would be okay for you, try with php 7.0 and 7.2 first.
This should be working at the current state (including the admin login).

**Comment by joseborges** [comment]
Maybe i'm doing something wrong :(

![image](https://user-images.githubusercontent.com/7250506/91635640-f7159b80-e9f1-11ea-8d6e-0a82f7068784.png)

**Comment by joseborges** [comment]
Ok, with PHP7.0 I can login... Is anyone looking into making this work on newer versions of PHP?

**Comment by joseborges** [comment]
Still some errors, but those I can see what's needs fixing :)

![image](https://user-images.githubusercontent.com/7250506/91635789-37294e00-e9f3-11ea-9bc7-df89c1222e6d.png)

**Comment by joseborges** [comment]
Thank you @nafbanap, at least now I have a working version on my pc.

I'll try to look into this project.

**Comment by MaDmaX1337** [comment]
I have the same problem, i cant login via php 7.3 on acp. Help please.

**Comment by MaDmaX1337** [comment]
Warning: session_start(): Failed to read session data: user (path: C:\xampp\tmp)

**Comment by soccerfan2** [comment]
Hello, i have problems with php 7.3 versions and higher versions. Installation seems ok but i'm not able to log-in the  Admin center login panel. Any idea? I have read that there is a login.php fix but is still not working for me. 
![ADMIN CENTER- No response](https://user-images.githubusercontent.com/81229758/112131414-d305eb80-8bc9-11eb-9605-27cf10085525.png)
Please help.
